openapi: 3.0.0
info:
  title: BrokerPortalApi
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /Proposal/SaveProposal:
    post:
      summary: Create New User
      operationId: post-user
      responses:
        '200':
          description: User Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
              examples:
                New User Bob Fellow:
                  value:
                    id: 12
                    firstName: Bob
                    lastName: Fellow
                    email: bob.fellow@gmail.com
                    dateOfBirth: '1996-08-24'
                    emailVerified: false
                    createDate: '2020-11-18'
        '400':
          description: Missing Required Information
        '409':
          description: Email Already Taken
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                firstName:
                  type: string
                lastName:
                  type: string
                email:
                  type: string
                dateOfBirth:
                  type: string
                  format: date
              required:
                - firstName
                - lastName
                - email
                - dateOfBirth
            examples:
              Create User Bob Fellow:
                value:
                  firstName: Bob
                  lastName: Fellow
                  email: bob.fellow@gmail.com
                  dateOfBirth: '1996-08-24'
        description: Post the necessary fields for the API to create a new user.
      description: Create a new user.
    parameters: []
components:
  schemas:
    Proposal:
      title: Proposal
      type: object
      description: ''
      x-examples: {}
      properties:
        ProposalTypeId:
          type: integer
          description: Unique identifier for the given user.
        CompanyId:
          type: integer
        ComplementaryModalityId:
          type: integer
          format: email
        ComplementaryInsuredAmountValue:
          type: number
          format: date
          example: '1997-10-31'
        HasCoBroker:
          type: boolean
          description: Set to true if the user's email has been verified.
        CoBroker:
          type: object
      required:
        - ProposalTypeId
        - CompanyId
        - ComplementaryModalityId
        - ComplementaryModalityId
        - HasCoBroker
    Cobroker:
      title: Cobroker
      type: object
      properties:
        id:
          type: integer
        personId:
          type: string
        amout:
          type: number
        rate:
          type: number
